global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      - targets: ['localhost:5000'] # Assumindo que o Prometheus rodará localmente ou terá acesso à aplicação
    metrics_path: /api/metrics

