global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      - targets: ['<REPLACE_WITH_LOAD_BALANCER_DNS>'] # TODO: Replace with your Load Balancer DNS name
    metrics_path: /api/metrics