global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      - targets: ['devops-mini-project-lb-591531424.us-east-1.elb.amazonaws.com']
    metrics_path: /api/metrics